#!/usr/bin/expect

set fid [open /home/rscudeller/.bin/.pass]
set password [read $fid]
close $fid
spawn /usr/bin/ssh rscudeller@[lindex $argv 0]
expect {
-re ".*Are.*.*yes.*no.*" {
send "yes\n"
exp_continue
#look for the password prompt
}

"*?assword:*" {
send $password
send "\n"
interact
#The expect command will now return
}
}
