#!/usr/bin/expect

set fid [open /home/rscudeller/.bin/.pass]
set password [read $fid]
close $fid
spawn /usr/bin/ssh rscudeller@[lindex $argv 0]
expect {
-re ".*Are.*.*yes.*no.*" {
send "yes\n"
exp_continue
#look for the password prompt
}

"*?assword:*" {
send $password
send "\n"
exp_continue
#The expect command will now return
}
"$ " {
send "sudo su -"
send "\n"
exp_continue
}
"rscudeller:" {
send $password
send "\n"
interact
# Enter sudo su -
}
}
